version: '3.8'

services:
  django:
    build: .
    container_name: nblog-django
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=Nblog.settings
      - DJANGO_DEBUG=${DJANGO_DEBUG:-False}
    volumes:
      - ./:/app
      - staticfiles:/app/staticfiles
      - media:/app/media
    ports:
      - "8000:8000"
    networks:
      - nblog-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: nblog-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DJANGO_DB_NAME}
      MYSQL_USER: ${DJANGO_DB_USER}
      MYSQL_PASSWORD: ${DJANGO_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - nblog-network

  nginx:
    image: nginx:1.21-alpine
    container_name: nblog-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/nginx.conf
      - staticfiles:/app/staticfiles:ro
      - media:/app/media:ro
    depends_on:
      - django
    networks:
      - nblog-network

volumes:
  db_data:
  staticfiles:
  media:

networks:
  nblog-network:
    driver: bridge